apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: ux
  name: ux
spec:
  ports:
    - name: "nodejs"
      port: 8002
      targetPort: 8002
  selector:
    io.kompose.service: ux
status:
  loadBalancer: {}
