#!/bin/bash -x


for IMAGEID in $(docker images -a --digests | fgrep -v sha256 | awk '{print $4}' | fgrep -v IMAGE); do
    echo "Removing ${IMAGEID} ..."
    docker rmi -f ${IMAGEID}
done

echo "Pruning volumes ..."
docker volume prune -f
