#!/bin/bash

for CONTAINERID in $(docker ps -a | grep -v ^CONTAINER | awk '{print $1}'); do
    echo "Killing ${CONTAINERID} ..."
    docker kill ${CONTAINERID}
    echo "Removing ${CONTAINERID} ..."
    docker rm -f --volumes ${CONTAINERID}
done
for CONTAINERID in $(podman ps -a | grep -v ^CONTAINER | awk '{print $1}'); do
    echo "Killing ${CONTAINERID} ..."
    podman kill ${CONTAINERID}
    echo "Removing ${CONTAINERID} ..."
    podman rm -f --volumes ${CONTAINERID}
done
